# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 254d8cb9167668e35ae13edaa3ae7410955497e3b4a50ca73c1442e64a48a5a3b69434e6a5fcc07d614ed4d29bbb2cf5b27d0d01c6f2815ddc6b2239d95b2e5d

test:
  secret_key_base: 308d1deca4189f7ff951022674db9c7727d65bed451994af733bc67d52ba89c88c1501df92411e461dc66ad9157734a9505f747af67f3c0c997c659a3c0a4875

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
